# Generated by Django 4.2.7 on 2025-06-19 01:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('type', models.CharField(choices=[('ProviderSync', 'Provider Sync'), ('EpgDataSync', 'Epg Data Sync')], editable=False, max_length=20)),
                ('state', models.CharField(choices=[('Queued', 'Queued'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('last_attempt_started_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allow_stream_auto_deletion', models.BooleanField(blank=True, default=True, null=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='provider_manager.provider')),
            ],
            options={
                'indexes': [models.Index(fields=['state', 'created_at'], name='job_state_created_idx'), models.Index(fields=['job_id'], name='job_jobid_idx')],
            },
        ),
    ]
