services:

  web:
    build:
      context: ./iptv_manager
      dockerfile: web.Dockerfile
    restart: always
    ports:
      - "8000:8000"
    environment:
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - ./config:/config
    depends_on:
      - migration

  job-worker:
    build:
      context: ./IPTV.JobWorker
      dockerfile: Dockerfile
    restart: always
    environment:
      - RABBITMQ_HOST=rabbitmq
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ./config:/config
    depends_on:
      - migration

  migration:
    build:
      context: ./iptv_manager
      dockerfile: task-worker.Dockerfile
    volumes:
      - ./config:/config
    command: python manage.py migrate
    healthcheck:
      test: ["NONE"]
      disable: true

  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

volumes:
  rabbitmq_data: