services:

  web:
    build:
      context: ./iptv_manager
      dockerfile: web.Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
    depends_on:
      - migration

  job-worker:
    build:
      context: ./IPTV.JobWorker
      dockerfile: Dockerfile
    restart: always
    environment:
      - DOTNET_ENVIRONMENT=Development
    volumes:
      - ./config:/config
    depends_on:
      - migration

  migration:
    build:
      context: ./iptv_manager
      dockerfile: web.Dockerfile
    volumes:
      - ./config:/config
    command: python manage.py migrate
    healthcheck:
      test: ["NONE"]
      disable: true