services:

  web:
    build:
      context: ./iptv_manager
      dockerfile: web.Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./iptv_manager/config:/config
    depends_on:
      - migration

  task-worker:
    build:
      context: ./iptv_manager
      dockerfile: task-worker.Dockerfile
    restart: always
    volumes:
      - ./iptv_manager/config:/config
    depends_on:
      - migration

  migration:
    build:
      context: ./iptv_manager
      dockerfile: task-worker.Dockerfile
    volumes:
      - ./iptv_manager/config:/config
    command: python manage.py migrate