services:

  web:
    build:
      context: ./web
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./config:/config
    depends_on:
      - migration

  job-worker:
    build: ./IPTV.JobWorker
    restart: always
    environment:
      - DOTNET_ENVIRONMENT=Development
      - EPG_SERVICE=http://epg-service:3000
    volumes:
      - ./config:/config
    depends_on:
      - epg-worker
      - migration
  
  epg-service:
    build: ./epg
    ports:
      - "3000:3000"
    volumes:
      - ./config:/config
    environment:
      - MAX_CONNECTIONS=1
      - DAYS=14
      - GZIP=false

  migration:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./config:/config
    command: python manage.py migrate
    healthcheck:
      test: ["NONE"]
      disable: true