services:

  kong:
    image: kong:latest
    restart: always
    environment:
      - KONG_DATABASE=off
#      - KONG_PG_HOST=db
#      - KONG_PG_USER=postgres
#      - KONG_PG_PASSWORD=postgres
      - KONG_DECLARATIVE_CONFIG=/etc/kong/kong.yml
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_ADMIN_GUI_URL=http://localhost:8002
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
    volumes:
      - ./config/kong/kong.yml:/etc/kong/kong.yml
    ports:
      - "8000-8004:8000-8004"
      - "8443-8445:8443-8445"
    depends_on:
      - web
      - playlist-manager
      - redisinsight
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  web:
    build:
      context: ./iptv_manager
    restart: always
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - PLAYLIST_MANAGER_URL=/api/playlist-manager
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/health/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  playlist-manager:
    build:
      context: ./IPTV.PlaylistManager
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_DB=playlist_manager
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s


  db:
    image: postgres:17-alpine
    restart: always
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  redisinsight:
    image: redis/redisinsight:latest
    restart: always
    volumes:
      - redisinsight_data:/data
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - "5540:5540"
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:5540/api/health/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

volumes:
  postgres_data:
  redis_data:
  redisinsight_data:
