# Generated by Django 4.2.7 on 2025-06-16 02:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('state', models.CharField(choices=[('Queued', 'Queued'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('last_attempt_started_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(blank=True, null=True)),
                ('allow_stream_auto_deletion', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='provider_manager.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ProviderStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tvg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('media_url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('logo_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='provider_manager.provider')),
            ],
        ),
    ]
