# Generated by Django 4.2.7 on 2025-06-19 04:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('is_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('tvg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('media_url', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('logo_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('group', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='provider_manager.provider')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'is_active'], name='stream_provider_active_idx'), models.Index(fields=['group', 'title', 'tvg_id'], name='stream_group_title_tvg_id_idx'), models.Index(fields=['is_active'], name='provider_stream_active_idx')],
            },
        ),
    ]
