# Generated by Django 4.2.7 on 2025-06-19 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_manager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProviderSyncJob',
        ),
    ]
