_format_version: "3.0"
_transform: true

services:
  - name: playlist-manager-service
    url: http://playlist-manager:8080
    routes:
      - name: playlist-manager-route
        paths:
          - /api/playlist-manager
        strip_path: true
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Origin
            - Authorization
            - Content-Type
          exposed_headers:
            - Content-Length
          max_age: 3600
          credentials: false
          preflight_continue: false

  - name: web-ui-service
    url: http://web:8000
    routes:
      - name: web-api-route
        paths:
          - /api/server-time
          - /api/resource-utilization
        strip_path: false
      - name: web-ui-route
        paths:
          - /
        strip_path: false
    plugins:
      - name: cors
        config:
          origins:
            - "*"
          methods:
            - GET
            - POST
            - PUT
            - DELETE
            - OPTIONS
          headers:
            - Origin
            - Authorization
            - Content-Type
          exposed_headers:
            - Content-Length
          max_age: 3600
          credentials: false
          preflight_continue: false
