# Generated by Django 4.2.7 on 2025-06-04 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistsource',
            name='url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='playlistsourcechannel',
            name='logo_url',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()]),
        ),
        migrations.AlterField(
            model_name='playlistsourcechannel',
            name='media_url',
            field=models.TextField(validators=[django.core.validators.URLValidator()]),
        ),
    ]
