# Generated by Django 4.2.7 on 2025-06-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_manager', '0002_alter_playlistsource_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistsourceinvocation',
            name='completed',
            field=models.BooleanField(default=False),
        ),
    ]
