# Generated by Django 4.2.7 on 2025-06-17 22:37

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xmltv_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('network', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('is_nsfw', models.BooleanField(default=False)),
                ('launched_at', models.DateField(blank=True, null=True)),
                ('closed_at', models.DateField(blank=True, null=True)),
                ('website_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('logo_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('categories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='guide_manager.category')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('flag', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.CharField(max_length=255)),
                ('site_id', models.CharField(max_length=255)),
                ('site_name', models.CharField(max_length=255)),
                ('lang', models.CharField(max_length=20)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guides', to='guide_manager.channel')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='guide_manager.country'),
        ),
        migrations.AddField(
            model_name='channel',
            name='replaced_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_channels', to='guide_manager.channel'),
        ),
    ]
