# Generated by Django 4.2.7 on 2025-06-16 06:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('starting_channel_number', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('tvg_id', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='playlist_manager.playlist')),
                ('provider_stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_channels', to='provider_manager.providerstream')),
            ],
            options={
                'indexes': [models.Index(fields=['playlist', 'order'], name='playlist_channel_order_idx'), models.Index(fields=['playlist', 'category'], name='playlist_channel_category_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='playlistchannel',
            constraint=models.UniqueConstraint(fields=('playlist', 'order'), name='unique_playlist_channel_order'),
        ),
        migrations.AddConstraint(
            model_name='playlistchannel',
            constraint=models.UniqueConstraint(fields=('playlist', 'provider_stream'), name='unique_playlist_channel_provider_stream'),
        ),
    ]
