# Generated by Django 4.2.7 on 2025-06-11 20:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider_manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('logo_url', models.TextField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('order', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='playlist_manager.playlist')),
                ('provider_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_channels', to='provider_manager.providerchannel')),
            ],
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['order'], name='playlist_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlist',
            constraint=models.UniqueConstraint(fields=('order',), name='unique_playlist_order'),
        ),
        migrations.AddIndex(
            model_name='playlistchannel',
            index=models.Index(fields=['playlist', 'order'], name='playlist_channel_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='playlistchannel',
            constraint=models.UniqueConstraint(fields=('playlist', 'order'), name='unique_playlist_channel_order'),
        ),
    ]
