# Generated by Django 4.2.7 on 2025-06-13 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_manager', '0003_remove_playlist_unique_playlist_order_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='playlistchannel',
            constraint=models.UniqueConstraint(fields=('playlist', 'provider_channel'), name='unique_playlist_channel_provider_channel'),
        ),
    ]
