# Generated by Django 4.2.7 on 2025-06-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_manager', '0004_playlistchannel_unique_playlist_channel_provider_channel'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='playlistchannel',
            index=models.Index(fields=['playlist', 'category'], name='playlist_channel_category_idx'),
        ),
    ]
