# Generated by Django 4.2.7 on 2025-06-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('playlist_manager', '0005_playlistchannel_playlist_channel_category_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='starting_channel_number',
            field=models.IntegerField(default=1),
        ),
    ]
