# Generated by Django 4.2.7 on 2025-06-09 22:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('provider_manager', '0003_playlistsourceinvocation_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistSyncJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('state', models.CharField(choices=[('Queued', 'Queued'), ('InProgress', 'In Progress'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Queued', max_length=20)),
                ('status_description', models.TextField(blank=True, null=True)),
                ('last_attempt_started_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(blank=True, null=True)),
                ('allow_channel_auto_deletion', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='provider_manager.playlistsource')),
            ],
        ),
        migrations.DeleteModel(
            name='PlaylistSourceInvocation',
        ),
    ]
