# Generated by Django 4.2.7 on 2025-06-10 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_manager', '0004_playlistsyncjob_delete_playlistsourceinvocation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlaylistSource',
            new_name='Provider',
        ),
        migrations.RenameModel(
            old_name='PlaylistSourceChannel',
            new_name='ProviderChannel',
        ),
        migrations.RenameModel(
            old_name='PlaylistSyncJob',
            new_name='ProviderSyncJob',
        ),
    ]
