# Generated by Django 4.2.7 on 2025-06-10 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_manager', '0005_rename_playlistsource_provider_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='providerchannel',
            old_name='source',
            new_name='provider',
        ),
        migrations.RenameField(
            model_name='providersyncjob',
            old_name='source',
            new_name='provider',
        ),
    ]
